### ISSUE TITLE
TODO 

### ISSUE THREAD

**Issue by zfengg** [zfengg/PayGroups.jl#3]
Features to add:
- [ ] work out an elegant way of `PayGroup` I/O.
- [x] immigrate the `Date` to here.
- [ ] create an independent web interface.
- [ ] ...
